# TODO: add in functions roxygen description instead if the function uses the library

library(dplyr)
library(magrittr)
library(Biostrings)
library(genbankr)
library(coRdon)
library(stringr)
library(grDevices)
library(reutils)
library(pkgload)
library(rmarkdown)
library(shape)
library(diagram)
library(gplots)